(
  define
  (problem instance-5)
  (:domain tpp-propositional)
  (:objects market1 level13 truck5 truck7 market8 goods9 truck4 depot4 level2 level9 depot5 market7 level1 market4 level7 goods4 level3 goods2 level5 level6 level0 level11 truck3 level10 level14 level12 truck2 level4 goods1 goods8 depot1 level15 depot6 truck1 truck6 depot2 goods5 goods7 market3 depot3 market6 goods10 goods3 goods6 market5 level8 market2)
  (
    :init
    (on-sale goods2 market8 level0)
    (ready-to-load goods3 market6 level0)
    (ready-to-load goods6 market1 level0)
    (connected market3 market5)
    (connected market4 market7)
    (on-sale goods2 market3 level1)
    (ready-to-load goods9 market6 level0)
    (loaded goods9 truck1 level0)
    (ready-to-load goods3 market4 level0)
    (connected market8 market2)
    (ready-to-load goods2 market6 level0)
    (on-sale goods2 market5 level2)
    (loaded goods1 truck2 level0)
    (ready-to-load goods9 market8 level0)
    (connected market6 market1)
    (connected depot1 market4)
    (connected market5 depot6)
    (next level10 level9)
    (on-sale goods10 market4 level3)
    (on-sale goods5 market6 level0)
    (loaded goods6 truck3 level0)
    (place_________ market6)
    (on-sale goods10 market7 level0)
    (loaded goods7 truck2 level0)
    (connected market1 market5)
    (place_________ depot2)
    (ready-to-load goods1 market7 level0)
    (stored goods2 level0)
    (on-sale goods10 market2 level0)
    (ready-to-load goods7 market3 level0)
    (ready-to-load goods7 market7 level0)
    (connected market4 market8)
    (truck_________ truck4)
    (connected market4 market2)
    (on-sale goods7 market2 level0)
    (at truck7 depot4)
    (stored goods6 level0)
    (connected market6 market3)
    (ready-to-load goods6 market4 level0)
    (ready-to-load goods5 market3 level0)
    (next level6 level5)
    (level_________ level0)
    (connected market6 market5)
    (at truck3 depot1)
    (on-sale goods7 market1 level2)
    (ready-to-load goods8 market5 level0)
    (locatable_____ goods6)
    (locatable_____ truck6)
    (ready-to-load goods5 market1 level0)
    (connected market4 depot1)
    (ready-to-load goods4 market1 level0)
    (truck_________ truck5)
    (ready-to-load goods1 market1 level0)
    (ready-to-load goods8 market2 level0)
    (loaded goods5 truck1 level0)
    (connected market7 depot4)
    (connected market1 market2)
    (ready-to-load goods1 market5 level0)
    (on-sale goods4 market2 level3)
    (stored goods4 level0)
    (ready-to-load goods4 market8 level0)
    (connected market6 market2)
    (loaded goods4 truck6 level0)
    (locatable_____ truck7)
    (ready-to-load goods7 market5 level0)
    (ready-to-load goods1 market8 level0)
    (ready-to-load goods8 market3 level0)
    (on-sale goods8 market3 level2)
    (locatable_____ goods9)
    (ready-to-load goods6 market7 level0)
    (ready-to-load goods7 market8 level0)
    (next level5 level4)
    (place_________ market3)
    (on-sale goods8 market4 level0)
    (ready-to-load goods9 market3 level0)
    (depot_________ depot3)
    (connected market7 market3)
    (on-sale goods9 market2 level0)
    (place_________ market5)
    (on-sale goods3 market1 level0)
    (on-sale goods8 market1 level0)
    (loaded goods2 truck5 level0)
    (ready-to-load goods7 market4 level0)
    (place_________ market4)
    (ready-to-load goods8 market6 level0)
    (connected market2 market7)
    (on-sale goods1 market5 level1)
    (loaded goods5 truck4 level0)
    (loaded goods5 truck5 level0)
    (loaded goods10 truck7 level0)
    (on-sale goods10 market1 level2)
    (goods_________ goods6)
    (locatable_____ goods10)
    (loaded goods1 truck4 level0)
    (connected depot5 market1)
    (connected market3 market7)
    (depot_________ depot6)
    (place_________ market2)
    (on-sale goods3 market7 level0)
    (loaded goods1 truck3 level0)
    (loaded goods1 truck6 level0)
    (level_________ level7)
    (on-sale goods9 market3 level1)
    (next level8 level7)
    (on-sale goods4 market4 level4)
    (locatable_____ goods4)
    (loaded goods7 truck1 level0)
    (connected market3 market4)
    (goods_________ goods9)
    (truck_________ truck1)
    (ready-to-load goods6 market6 level0)
    (ready-to-load goods6 market5 level0)
    (level_________ level3)
    (at truck6 depot6)
    (loaded goods4 truck3 level0)
    (depot_________ depot4)
    (on-sale goods4 market5 level0)
    (on-sale goods5 market7 level0)
    (ready-to-load goods6 market2 level0)
    (loaded goods8 truck5 level0)
    (connected market3 market8)
    (connected market3 market2)
    (stored goods8 level0)
    (connected market2 market1)
    (on-sale goods1 market2 level0)
    (on-sale goods8 market5 level2)
    (connected market5 depot3)
    (ready-to-load goods9 market4 level0)
    (ready-to-load goods3 market8 level0)
    (connected market2 market5)
    (on-sale goods4 market3 level2)
    (loaded goods8 truck2 level0)
    (goods_________ goods10)
    (at truck2 depot3)
    (ready-to-load goods2 market8 level0)
    (ready-to-load goods9 market1 level0)
    (connected market6 market4)
    (loaded goods9 truck7 level0)
    (loaded goods10 truck2 level0)
    (depot_________ depot2)
    (on-sale goods4 market7 level1)
    (ready-to-load goods2 market1 level0)
    (level_________ level10)
    (loaded goods6 truck1 level0)
    (goods_________ goods4)
    (locatable_____ goods3)
    (ready-to-load goods2 market5 level0)
    (on-sale goods5 market1 level0)
    (loaded goods2 truck1 level0)
    (loaded goods4 truck1 level0)
    (ready-to-load goods5 market6 level0)
    (ready-to-load goods10 market7 level0)
    (on-sale goods4 market6 level0)
    (level_________ level9)
    (loaded goods10 truck3 level0)
    (loaded goods3 truck5 level0)
    (ready-to-load goods5 market5 level0)
    (on-sale goods1 market6 level0)
    (connected market8 market1)
    (ready-to-load goods10 market2 level0)
    (ready-to-load goods5 market2 level0)
    (connected depot4 market7)
    (on-sale goods1 market7 level4)
    (ready-to-load goods7 market2 level0)
    (connected market2 market6)
    (locatable_____ truck3)
    (next level11 level10)
    (ready-to-load goods6 market3 level0)
    (next level14 level13)
    (market________ market8)
    (on-sale goods2 market4 level0)
    (loaded goods3 truck2 level0)
    (stored goods3 level0)
    (connected market3 market6)
    (level_________ level2)
    (ready-to-load goods4 market4 level0)
    (on-sale goods1 market4 level0)
    (locatable_____ truck2)
    (loaded goods9 truck4 level0)
    (level_________ level4)
    (on-sale goods5 market4 level0)
    (loaded goods6 truck5 level0)
    (loaded goods2 truck4 level0)
    (loaded goods4 truck4 level0)
    (loaded goods3 truck3 level0)
    (loaded goods9 truck3 level0)
    (on-sale goods6 market5 level2)
    (loaded goods4 truck7 level0)
    (goods_________ goods3)
    (connected market1 market6)
    (loaded goods2 truck3 level0)
    (loaded goods1 truck7 level0)
    (loaded goods2 truck6 level0)
    (connected market1 market8)
    (ready-to-load goods10 market8 level0)
    (loaded goods1 truck1 level0)
    (on-sale goods10 market8 level2)
    (ready-to-load goods7 market1 level0)
    (ready-to-load goods2 market2 level0)
    (on-sale goods7 market5 level1)
    (depot_________ depot5)
    (loaded goods2 truck2 level0)
    (ready-to-load goods5 market8 level0)
    (loaded goods5 truck6 level0)
    (ready-to-load goods7 market6 level0)
    (on-sale goods7 market6 level2)
    (ready-to-load goods9 market7 level0)
    (connected market8 depot2)
    (on-sale goods6 market4 level3)
    (on-sale goods9 market5 level0)
    (ready-to-load goods2 market7 level0)
    (ready-to-load goods4 market7 level0)
    (on-sale goods7 market8 level4)
    (place_________ depot1)
    (next level15 level14)
    (ready-to-load goods3 market1 level0)
    (level_________ level8)
    (ready-to-load goods8 market1 level0)
    (ready-to-load goods3 market5 level0)
    (connected market2 market3)
    (connected market7 market5)
    (truck_________ truck6)
    (loaded goods8 truck1 level0)
    (on-sale goods7 market4 level2)
    (next level13 level12)
    (ready-to-load goods3 market2 level0)
    (locatable_____ truck4)
    (market________ market7)
    (loaded goods8 truck6 level0)
    (loaded goods10 truck1 level0)
    (connected depot3 market5)
    (connected market2 market4)
    (on-sale goods6 market3 level4)
    (stored goods5 level0)
    (truck_________ truck7)
    (loaded goods7 truck4 level0)
    (ready-to-load goods3 market7 level0)
    (ready-to-load goods6 market8 level0)
    (loaded goods5 truck3 level0)
    (market________ market4)
    (next level3 level2)
    (on-sale goods3 market6 level0)
    (on-sale goods9 market6 level2)
    (loaded goods5 truck2 level0)
    (connected market7 market4)
    (on-sale goods3 market4 level0)
    (stored goods7 level0)
    (loaded goods7 truck3 level0)
    (loaded goods7 truck6 level0)
    (level_________ level15)
    (connected market5 market1)
    (connected market2 market8)
    (level_________ level5)
    (on-sale goods2 market6 level0)
    (at truck4 depot1)
    (on-sale goods9 market8 level0)
    (connected market1 depot5)
    (connected market5 market3)
    (locatable_____ truck5)
    (ready-to-load goods4 market5 level0)
    (ready-to-load goods5 market7 level0)
    (market________ market2)
    (place_________ market8)
    (on-sale goods5 market5 level0)
    (ready-to-load goods1 market3 level0)
    (loaded goods3 truck4 level0)
    (connected market7 market6)
    (loaded goods8 truck4 level0)
    (connected market8 market3)
    (connected market7 market2)
    (on-sale goods3 market2 level1)
    (connected market7 market8)
    (stored goods9 level0)
    (ready-to-load goods4 market2 level0)
    (loaded goods10 truck5 level0)
    (loaded goods3 truck7 level0)
    (next level2 level1)
    (on-sale goods5 market2 level0)
    (on-sale goods8 market8 level3)
    (ready-to-load goods1 market2 level0)
    (on-sale goods7 market3 level2)
    (on-sale goods7 market7 level0)
    (connected market8 market5)
    (market________ market1)
    (locatable_____ goods8)
    (loaded goods3 truck6 level0)
    (ready-to-load goods4 market3 level0)
    (loaded goods2 truck7 level0)
    (connected market6 market7)
    (level_________ level12)
    (loaded goods7 truck5 level0)
    (loaded goods9 truck5 level0)
    (connected market4 market3)
    (on-sale goods9 market7 level3)
    (next level9 level8)
    (connected market5 market4)
    (ready-to-load goods8 market7 level0)
    (loaded goods8 truck3 level0)
    (loaded goods6 truck4 level0)
    (on-sale goods9 market1 level4)
    (on-sale goods3 market5 level4)
    (connected market4 market5)
    (ready-to-load goods10 market5 level0)
    (at truck1 depot4)
    (on-sale goods10 market5 level2)
    (level_________ level11)
    (on-sale goods4 market1 level0)
    (on-sale goods2 market7 level2)
    (level_________ level13)
    (ready-to-load goods4 market6 level0)
    (on-sale goods1 market1 level0)
    (on-sale goods8 market2 level0)
    (loaded goods9 truck6 level0)
    (ready-to-load goods1 market6 level0)
    (connected market5 market6)
    (loaded goods6 truck6 level0)
    (connected market5 market8)
    (connected market5 market2)
    (stored goods10 level0)
    (locatable_____ goods2)
    (next level4 level3)
    (on-sale goods1 market8 level0)
    (on-sale goods6 market7 level0)
    (goods_________ goods8)
    (locatable_____ goods7)
    (market________ market6)
    (ready-to-load goods10 market3 level0)
    (ready-to-load goods2 market4 level0)
    (locatable_____ truck1)
    (place_________ depot5)
    (place_________ market7)
    (locatable_____ goods1)
    (level_________ level14)
    (ready-to-load goods10 market4 level0)
    (on-sale goods8 market7 level1)
    (on-sale goods6 market1 level1)
    (ready-to-load goods1 market4 level0)
    (ready-to-load goods5 market4 level0)
    (on-sale goods2 market1 level3)
    (locatable_____ goods5)
    (connected depot6 market5)
    (connected market4 market6)
    (on-sale goods8 market6 level2)
    (stored goods1 level0)
    (place_________ depot3)
    (ready-to-load goods10 market1 level0)
    (ready-to-load goods8 market8 level0)
    (loaded goods4 truck5 level0)
    (at truck5 depot2)
    (ready-to-load goods10 market6 level0)
    (on-sale goods10 market6 level2)
    (loaded goods5 truck7 level0)
    (level_________ level6)
    (next level7 level6)
    (loaded goods9 truck2 level0)
    (loaded goods6 truck2 level0)
    (loaded goods7 truck7 level0)
    (on-sale goods6 market8 level0)
    (truck_________ truck3)
    (next level1 level0)
    (ready-to-load goods3 market3 level0)
    (loaded goods4 truck2 level0)
    (on-sale goods3 market3 level2)
    (depot_________ depot1)
    (goods_________ goods2)
    (ready-to-load goods9 market5 level0)
    (on-sale goods5 market3 level3)
    (place_________ market1)
    (ready-to-load goods8 market4 level0)
    (level_________ level1)
    (place_________ depot6)
    (on-sale goods6 market6 level0)
    (ready-to-load goods2 market3 level0)
    (on-sale goods1 market3 level3)
    (ready-to-load goods9 market2 level0)
    (connected market5 market7)
    (goods_________ goods7)
    (truck_________ truck2)
    (goods_________ goods1)
    (on-sale goods6 market2 level0)
    (connected market8 market7)
    (connected depot2 market8)
    (loaded goods3 truck1 level0)
    (loaded goods8 truck7 level0)
    (goods_________ goods5)
    (on-sale goods4 market8 level4)
    (loaded goods10 truck4 level0)
    (market________ market3)
    (place_________ depot4)
    (loaded goods1 truck5 level0)
    (connected market8 market4)
    (on-sale goods9 market4 level0)
    (on-sale goods3 market8 level0)
    (loaded goods6 truck7 level0)
    (on-sale goods2 market2 level1)
    (market________ market5)
    (on-sale goods5 market8 level3)
    (next level12 level11)
    (loaded goods10 truck6 level0)
    (on-sale goods10 market3 level4)
    (injected------0)
  )
  (
    :goal
    (
      and
      (stored goods1 level5)
      (stored goods2 level3)
      (stored goods3 level2)
      (stored goods4 level4)
      (stored goods5 level4)
      (stored goods6 level5)
      (stored goods7 level1)
      (stored goods8 level9)
      (stored goods9 level9)
      (stored goods10 level15)
      (injected------0)
    )
  )
)