(
  define
  (problem instance-4)
  (:domain tpp-propositional)
  (:objects market1 level13 truck5 truck7 truck4 depot4 level2 level9 depot5 level1 market4 level7 goods4 level3 goods2 level5 level6 level0 level11 truck3 level10 level14 level12 truck2 level4 goods1 depot1 truck1 truck6 depot2 goods5 goods7 market3 depot3 market6 goods3 goods6 market5 level8 market2)
  (
    :init
    (ready-to-load goods3 market6 level0)
    (ready-to-load goods6 market1 level0)
    (loaded goods4 truck7 level0)
    (goods_________ goods3)
    (connected market1 market6)
    (loaded goods2 truck3 level0)
    (ready-to-load goods3 market4 level0)
    (loaded goods1 truck7 level0)
    (loaded goods2 truck6 level0)
    (loaded goods1 truck1 level0)
    (on-sale goods2 market1 level0)
    (ready-to-load goods7 market1 level0)
    (ready-to-load goods2 market6 level0)
    (ready-to-load goods2 market2 level0)
    (connected market1 market3)
    (loaded goods1 truck2 level0)
    (on-sale goods7 market5 level1)
    (loaded goods2 truck2 level0)
    (depot_________ depot5)
    (connected market6 market1)
    (next level10 level9)
    (loaded goods5 truck6 level0)
    (loaded goods6 truck3 level0)
    (ready-to-load goods7 market6 level0)
    (place_________ market6)
    (on-sale goods3 market3 level0)
    (loaded goods7 truck2 level0)
    (on-sale goods3 market5 level3)
    (place_________ depot2)
    (stored goods2 level0)
    (connected market5 depot1)
    (on-sale goods2 market3 level0)
    (ready-to-load goods7 market3 level0)
    (truck_________ truck4)
    (on-sale goods5 market6 level4)
    (at truck1 depot1)
    (place_________ depot1)
    (on-sale goods7 market2 level0)
    (ready-to-load goods3 market1 level0)
    (level_________ level8)
    (stored goods6 level0)
    (ready-to-load goods3 market5 level0)
    (connected market2 market3)
    (connected market6 market3)
    (ready-to-load goods6 market4 level0)
    (ready-to-load goods5 market3 level0)
    (on-sale goods6 market4 level2)
    (truck_________ truck6)
    (next level6 level5)
    (next level13 level12)
    (level_________ level0)
    (connected market6 market5)
    (ready-to-load goods3 market2 level0)
    (on-sale goods4 market4 level2)
    (on-sale goods3 market2 level2)
    (locatable_____ truck4)
    (at truck3 depot1)
    (locatable_____ goods6)
    (stored goods5 level0)
    (truck_________ truck7)
    (locatable_____ truck6)
    (ready-to-load goods5 market1 level0)
    (loaded goods7 truck4 level0)
    (ready-to-load goods4 market1 level0)
    (truck_________ truck5)
    (connected market2 depot3)
    (loaded goods5 truck3 level0)
    (market________ market4)
    (next level3 level2)
    (ready-to-load goods1 market1 level0)
    (loaded goods5 truck1 level0)
    (on-sale goods6 market1 level0)
    (connected market1 market2)
    (connected depot4 market6)
    (at truck5 depot5)
    (ready-to-load goods1 market5 level0)
    (loaded goods5 truck2 level0)
    (stored goods7 level0)
    (stored goods4 level0)
    (loaded goods7 truck3 level0)
    (loaded goods7 truck6 level0)
    (on-sale goods7 market1 level0)
    (connected market6 market2)
    (connected market6 depot2)
    (on-sale goods2 market6 level0)
    (loaded goods4 truck6 level0)
    (locatable_____ truck7)
    (ready-to-load goods7 market5 level0)
    (at truck4 depot1)
    (level_________ level5)
    (on-sale goods5 market4 level5)
    (locatable_____ truck5)
    (locatable_____ goods4)
    (ready-to-load goods4 market5 level0)
    (market________ market2)
    (on-sale goods7 market6 level0)
    (ready-to-load goods1 market3 level0)
    (next level5 level4)
    (loaded goods3 truck4 level0)
    (place_________ market3)
    (on-sale goods3 market4 level4)
    (depot_________ depot3)
    (ready-to-load goods4 market2 level0)
    (on-sale goods4 market2 level2)
    (loaded goods3 truck7 level0)
    (next level2 level1)
    (ready-to-load goods1 market2 level0)
    (on-sale goods5 market2 level0)
    (on-sale goods7 market3 level0)
    (market________ market1)
    (place_________ market5)
    (loaded goods3 truck6 level0)
    (ready-to-load goods4 market3 level0)
    (loaded goods2 truck5 level0)
    (ready-to-load goods7 market4 level0)
    (loaded goods2 truck7 level0)
    (connected depot3 market2)
    (on-sale goods3 market6 level2)
    (place_________ market4)
    (on-sale goods5 market3 level0)
    (connected market4 market1)
    (loaded goods7 truck5 level0)
    (level_________ level12)
    (loaded goods5 truck4 level0)
    (loaded goods5 truck5 level0)
    (on-sale goods5 market5 level5)
    (goods_________ goods6)
    (connected market4 market3)
    (loaded goods1 truck4 level0)
    (next level9 level8)
    (connected market5 market4)
    (loaded goods6 truck4 level0)
    (on-sale goods4 market5 level1)
    (level_________ level11)
    (connected market4 market5)
    (place_________ market2)
    (on-sale goods4 market1 level0)
    (loaded goods1 truck3 level0)
    (ready-to-load goods4 market6 level0)
    (loaded goods1 truck6 level0)
    (level_________ level13)
    (connected depot5 market5)
    (next level8 level7)
    (on-sale goods1 market1 level0)
    (on-sale goods6 market3 level1)
    (level_________ level7)
    (loaded goods7 truck1 level0)
    (ready-to-load goods1 market6 level0)
    (connected market3 market4)
    (loaded goods6 truck6 level0)
    (connected market5 market6)
    (on-sale goods3 market1 level3)
    (at truck7 depot2)
    (truck_________ truck1)
    (ready-to-load goods6 market6 level0)
    (ready-to-load goods6 market5 level0)
    (level_________ level3)
    (locatable_____ goods2)
    (next level4 level3)
    (on-sale goods6 market5 level4)
    (loaded goods4 truck3 level0)
    (depot_________ depot4)
    (ready-to-load goods6 market2 level0)
    (at truck2 depot2)
    (connected market1 market4)
    (connected market3 market2)
    (connected market2 market1)
    (connected depot2 market6)
    (on-sale goods1 market3 level0)
    (locatable_____ goods7)
    (ready-to-load goods2 market4 level0)
    (locatable_____ truck1)
    (market________ market6)
    (place_________ depot5)
    (locatable_____ goods1)
    (on-sale goods2 market2 level4)
    (level_________ level14)
    (ready-to-load goods1 market4 level0)
    (on-sale goods1 market2 level0)
    (ready-to-load goods5 market4 level0)
    (locatable_____ goods5)
    (connected market3 market1)
    (on-sale goods4 market3 level0)
    (on-sale goods2 market5 level3)
    (on-sale goods7 market4 level0)
    (stored goods1 level0)
    (place_________ depot3)
    (loaded goods4 truck5 level0)
    (connected market6 depot4)
    (loaded goods5 truck7 level0)
    (depot_________ depot2)
    (level_________ level10)
    (ready-to-load goods2 market1 level0)
    (level_________ level6)
    (next level7 level6)
    (loaded goods6 truck1 level0)
    (goods_________ goods4)
    (connected depot1 market5)
    (locatable_____ goods3)
    (ready-to-load goods2 market5 level0)
    (loaded goods6 truck2 level0)
    (on-sale goods5 market1 level0)
    (loaded goods2 truck1 level0)
    (loaded goods4 truck1 level0)
    (ready-to-load goods5 market6 level0)
    (loaded goods7 truck7 level0)
    (truck_________ truck3)
    (next level1 level0)
    (ready-to-load goods3 market3 level0)
    (loaded goods4 truck2 level0)
    (on-sale goods4 market6 level0)
    (level_________ level9)
    (loaded goods3 truck5 level0)
    (depot_________ depot1)
    (goods_________ goods2)
    (ready-to-load goods5 market5 level0)
    (on-sale goods1 market6 level0)
    (place_________ market1)
    (level_________ level1)
    (on-sale goods6 market6 level0)
    (ready-to-load goods2 market3 level0)
    (ready-to-load goods5 market2 level0)
    (connected market5 depot5)
    (goods_________ goods7)
    (truck_________ truck2)
    (ready-to-load goods7 market2 level0)
    (connected market2 market6)
    (locatable_____ truck3)
    (goods_________ goods1)
    (next level11 level10)
    (on-sale goods6 market2 level0)
    (at truck6 depot5)
    (ready-to-load goods6 market3 level0)
    (next level14 level13)
    (loaded goods3 truck1 level0)
    (goods_________ goods5)
    (stored goods3 level0)
    (loaded goods3 truck2 level0)
    (connected market3 market6)
    (market________ market3)
    (level_________ level2)
    (ready-to-load goods4 market4 level0)
    (on-sale goods1 market4 level0)
    (place_________ depot4)
    (loaded goods1 truck5 level0)
    (on-sale goods1 market5 level5)
    (locatable_____ truck2)
    (level_________ level4)
    (loaded goods6 truck7 level0)
    (loaded goods6 truck5 level0)
    (market________ market5)
    (loaded goods2 truck4 level0)
    (next level12 level11)
    (loaded goods4 truck4 level0)
    (loaded goods3 truck3 level0)
    (on-sale goods2 market4 level4)
    (injected------0)
  )
  (
    :goal
    (
      and
      (stored goods1 level4)
      (stored goods2 level2)
      (stored goods3 level10)
      (stored goods4 level4)
      (stored goods5 level14)
      (stored goods6 level5)
      (stored goods7 level1)
      (injected------0)
    )
  )
)