(
  define
  (problem instance-1)
  (:domain tpp-propositional)
  (:objects market1 truck2 level4 goods1 depot1 truck1 depot2 level2 level9 level1 market4 level7 market3 depot3 level3 goods2 level5 level6 level0 level11 truck3 level10 goods3 market5 level8 market2)
  (
    :init
    (connected depot2 market3)
    (level_________ level11)
    (connected market3 market5)
    (goods_________ goods3)
    (connected market4 market5)
    (place_________ market2)
    (loaded goods2 truck3 level0)
    (ready-to-load goods3 market4 level0)
    (loaded goods1 truck1 level0)
    (on-sale goods2 market1 level0)
    (loaded goods1 truck3 level0)
    (level_________ level7)
    (next level8 level7)
    (ready-to-load goods2 market2 level0)
    (connected market1 market3)
    (loaded goods1 truck2 level0)
    (loaded goods2 truck2 level0)
    (connected market3 market4)
    (connected depot1 market4)
    (next level10 level9)
    (connected market5 market2)
    (truck_________ truck1)
    (on-sale goods3 market3 level0)
    (loaded goods3 truck3 level0)
    (level_________ level3)
    (at truck1 depot2)
    (place_________ depot2)
    (locatable_____ goods2)
    (next level4 level3)
    (stored goods2 level0)
    (at truck2 depot2)
    (on-sale goods2 market3 level0)
    (on-sale goods3 market2 level3)
    (connected market1 market4)
    (connected market3 market2)
    (connected market2 market1)
    (on-sale goods1 market3 level0)
    (connected market4 market2)
    (ready-to-load goods2 market4 level0)
    (place_________ depot1)
    (locatable_____ truck1)
    (ready-to-load goods3 market1 level0)
    (locatable_____ goods1)
    (level_________ level8)
    (ready-to-load goods1 market4 level0)
    (ready-to-load goods3 market5 level0)
    (connected market2 market3)
    (on-sale goods1 market2 level0)
    (connected market5 depot3)
    (on-sale goods3 market4 level1)
    (next level6 level5)
    (connected market3 market1)
    (connected market2 market5)
    (level_________ level0)
    (on-sale goods1 market1 level2)
    (ready-to-load goods3 market2 level0)
    (stored goods1 level0)
    (place_________ depot3)
    (on-sale goods1 market5 level3)
    (at truck3 depot1)
    (connected depot3 market5)
    (connected market2 market4)
    (connected market4 depot1)
    (on-sale goods1 market4 level6)
    (depot_________ depot2)
    (market________ market4)
    (ready-to-load goods2 market1 level0)
    (level_________ level10)
    (level_________ level6)
    (next level3 level2)
    (next level7 level6)
    (ready-to-load goods1 market1 level0)
    (locatable_____ goods3)
    (connected market1 market2)
    (ready-to-load goods2 market5 level0)
    (loaded goods2 truck1 level0)
    (on-sale goods2 market4 level5)
    (ready-to-load goods1 market5 level0)
    (truck_________ truck3)
    (next level1 level0)
    (ready-to-load goods3 market3 level0)
    (depot_________ depot1)
    (level_________ level9)
    (level_________ level5)
    (on-sale goods2 market2 level0)
    (on-sale goods2 market5 level0)
    (goods_________ goods2)
    (connected market5 market3)
    (place_________ market1)
    (level_________ level1)
    (market________ market2)
    (ready-to-load goods2 market3 level0)
    (ready-to-load goods1 market3 level0)
    (next level5 level4)
    (place_________ market3)
    (truck_________ truck2)
    (depot_________ depot3)
    (goods_________ goods1)
    (locatable_____ truck3)
    (next level11 level10)
    (next level2 level1)
    (ready-to-load goods1 market2 level0)
    (market________ market1)
    (place_________ market5)
    (loaded goods3 truck1 level0)
    (on-sale goods3 market1 level0)
    (stored goods3 level0)
    (loaded goods3 truck2 level0)
    (market________ market3)
    (level_________ level2)
    (place_________ market4)
    (on-sale goods3 market5 level0)
    (connected market3 depot2)
    (locatable_____ truck2)
    (level_________ level4)
    (connected market4 market1)
    (market________ market5)
    (connected market4 market3)
    (next level9 level8)
    (connected market5 market4)
    (injected------0)
  )
  (
    :goal
    (
      and
      (stored goods1 level8)
      (stored goods2 level3)
      (stored goods3 level1)
      (injected------0)
    )
  )
)