(
  define
  (problem instance-5)
  (:domain driverlog)
  (:objects package15 s3 truck5 truck7 p2-0 truck9 package14 truck4 package8 driver4 s6 truck10 package10 truck8 s0 driver3 p3-1 s5 p0-2 truck3 driver8 p1-3 driver1 p0-7 package9 truck2 package6 p4-7 driver7 truck1 driver5 truck6 package12 package5 p0-1 package7 s2 driver6 package1 p3-4 p2-6 package2 s1 s7 p1-0 package3 package4 package13 p4-5 p1-2 driver2 package11 s4)
  (
    :init
    (locatable truck3)
    (obj_____ package1)
    (link s1 s5)
    (locatable truck10)
    (locatable package6)
    (link s1 s7)
    (locatable truck9)
    (truck___ truck10)
    (path s1 p1-2)
    (truck___ truck9)
    (path s4 p4-7)
    (locatable package15)
    (truck___ truck1)
    (empty truck3)
    (path p0-2 s0)
    (locatable driver2)
    (empty truck10)
    (locatable package11)
    (link s1 s3)
    (path p2-6 s2)
    (empty truck9)
    (locatable package7)
    (link s4 s6)
    (locatable truck2)
    (at truck9 s6)
    (link s5 s1)
    (path s0 p0-1)
    (at package2 s5)
    (locatable driver3)
    (path s2 p1-2)
    (obj_____ package10)
    (empty truck2)
    (obj_____ package2)
    (link s2 s3)
    (at package7 s6)
    (link s1 s4)
    (path p3-4 s3)
    (location p4-5)
    (locatable driver6)
    (driver__ driver2)
    (at driver5 s4)
    (location s1)
    (link s6 s0)
    (link s3 s5)
    (locatable package2)
    (obj_____ package13)
    (locatable package9)
    (link s4 s3)
    (at truck5 s6)
    (location p0-1)
    (at driver1 s3)
    (driver__ driver6)
    (link s7 s6)
    (obj_____ package5)
    (truck___ truck3)
    (at driver8 s0)
    (link s7 s2)
    (link s5 s2)
    (link s0 s5)
    (link s3 s6)
    (at package10 s1)
    (path p1-3 s1)
    (link s7 s1)
    (locatable truck4)
    (driver__ driver4)
    (link s6 s3)
    (locatable driver5)
    (truck___ truck2)
    (locatable package13)
    (locatable truck8)
    (path s2 p0-2)
    (path p0-1 s0)
    (truck___ truck8)
    (obj_____ package12)
    (obj_____ package3)
    (locatable truck6)
    (location p0-2)
    (at truck1 s2)
    (empty truck4)
    (obj_____ package14)
    (locatable package1)
    (locatable package5)
    (location s4)
    (path p4-7 s7)
    (location s2)
    (empty truck8)
    (location p2-6)
    (at driver7 s6)
    (path s5 p4-5)
    (location p1-3)
    (empty truck6)
    (path p4-7 s4)
    (at driver4 s2)
    (at driver3 s7)
    (link s3 s1)
    (obj_____ package4)
    (locatable truck7)
    (truck___ truck7)
    (locatable truck5)
    (driver__ driver5)
    (locatable package10)
    (locatable driver4)
    (empty truck7)
    (at package3 s3)
    (link s2 s1)
    (empty truck5)
    (path s4 p4-5)
    (location s7)
    (path s1 p0-1)
    (locatable driver7)
    (locatable package4)
    (link s2 s5)
    (locatable driver8)
    (path p0-7 s7)
    (path s3 p1-3)
    (location p1-2)
    (path p0-7 s0)
    (path p0-2 s2)
    (truck___ truck4)
    (at package8 s6)
    (at package15 s4)
    (at package5 s1)
    (at truck2 s6)
    (link s3 s4)
    (location s6)
    (at truck7 s1)
    (obj_____ package8)
    (obj_____ package6)
    (link s3 s2)
    (driver__ driver7)
    (truck___ truck6)
    (at driver2 s5)
    (path p1-2 s2)
    (obj_____ package15)
    (obj_____ package11)
    (location s5)
    (path s7 p4-7)
    (path s0 p0-2)
    (path s6 p2-6)
    (driver__ driver8)
    (link s4 s1)
    (at truck3 s2)
    (link s0 s6)
    (path p1-2 s1)
    (path s0 p0-7)
    (path s7 p0-7)
    (path p2-6 s6)
    (at package14 s0)
    (at truck6 s5)
    (link s5 s0)
    (truck___ truck5)
    (at package13 s6)
    (locatable package12)
    (locatable package3)
    (at package4 s1)
    (locatable package14)
    (locatable package8)
    (location p2-0)
    (locatable truck1)
    (location p3-4)
    (location p3-1)
    (link s6 s1)
    (at truck4 s6)
    (path p3-4 s4)
    (empty truck1)
    (at package6 s3)
    (location s0)
    (driver__ driver1)
    (at package9 s1)
    (path s1 p1-3)
    (link s2 s7)
    (path p4-5 s5)
    (location p4-7)
    (at truck8 s7)
    (at package11 s5)
    (obj_____ package9)
    (path p1-3 s3)
    (at driver6 s3)
    (link s6 s7)
    (link s1 s6)
    (link s5 s3)
    (path s2 p2-6)
    (link s1 s2)
    (location p0-7)
    (at truck10 s7)
    (driver__ driver3)
    (at package12 s1)
    (at package1 s1)
    (obj_____ package7)
    (path s3 p3-4)
    (path s4 p3-4)
    (path p0-1 s1)
    (path p4-5 s4)
    (locatable driver1)
    (location s3)
    (location p1-0)
    (link s6 s4)
    (injected-0)
  )
  (
    :goal
    (
      and
      (at driver1 s7)
      (at driver2 s1)
      (at driver3 s2)
      (at driver4 s0)
      (at driver5 s4)
      (at driver6 s3)
      (at truck1 s7)
      (at truck2 s0)
      (at truck3 s4)
      (at truck4 s2)
      (at truck6 s4)
      (at truck7 s0)
      (at truck8 s4)
      (at truck9 s3)
      (at truck10 s3)
      (at package1 s6)
      (at package2 s5)
      (at package3 s7)
      (at package4 s5)
      (at package5 s3)
      (at package6 s1)
      (at package7 s2)
      (at package8 s2)
      (at package9 s0)
      (at package10 s0)
      (at package11 s2)
      (at package12 s7)
      (at package13 s2)
      (at package14 s4)
      (at package15 s5)
      (injected-0)
    )
  )
)