(
  define
  (problem instance-1)
  (:domain driverlog)
  (:objects s3 truck2 package6 truck1 driver5 truck4 package8 package5 p0-1 package7 driver4 s2 p2-3 package1 p3-0 p0-3 package10 s0 driver3 package2 s1 truck3 p1-3 package3 package4 p1-2 driver1 driver2 package9)
  (
    :init
    (obj_____ package1)
    (locatable truck3)
    (at driver4 s3)
    (locatable package6)
    (at package6 s1)
    (path s1 p0-1)
    (path s1 p1-2)
    (path s3 p2-3)
    (link s0 s2)
    (location p0-3)
    (truck___ truck1)
    (locatable package4)
    (empty truck3)
    (at package2 s2)
    (at truck1 s0)
    (locatable driver2)
    (link s1 s3)
    (at package7 s0)
    (locatable package7)
    (locatable truck2)
    (path s0 p0-1)
    (link s3 s0)
    (locatable driver3)
    (path s3 p1-3)
    (path s2 p1-2)
    (at driver1 s2)
    (location p1-2)
    (obj_____ package10)
    (path p0-3 s3)
    (truck___ truck4)
    (empty truck2)
    (obj_____ package2)
    (link s2 s3)
    (at truck2 s2)
    (obj_____ package6)
    (obj_____ package8)
    (link s3 s2)
    (at package8 s1)
    (path p1-2 s2)
    (path p2-3 s2)
    (driver__ driver2)
    (location s1)
    (at package5 s3)
    (at driver5 s0)
    (at driver2 s3)
    (path p1-2 s1)
    (path s3 p0-3)
    (at driver3 s0)
    (locatable package2)
    (locatable package3)
    (locatable package9)
    (locatable package8)
    (path p2-3 s3)
    (at package1 s3)
    (location p0-1)
    (locatable truck1)
    (obj_____ package5)
    (truck___ truck3)
    (at package9 s2)
    (empty truck1)
    (path p1-3 s1)
    (link s1 s0)
    (location s0)
    (link s0 s1)
    (driver__ driver1)
    (path s1 p1-3)
    (locatable truck4)
    (driver__ driver4)
    (locatable driver5)
    (truck___ truck2)
    (path s0 p0-3)
    (path p0-1 s0)
    (at package10 s3)
    (obj_____ package3)
    (location p3-0)
    (path p1-3 s3)
    (obj_____ package9)
    (link s0 s3)
    (empty truck4)
    (path p0-3 s0)
    (link s2 s0)
    (locatable package5)
    (locatable package1)
    (link s1 s2)
    (location s2)
    (at package4 s0)
    (location p1-3)
    (path s2 p2-3)
    (location p2-3)
    (link s3 s1)
    (obj_____ package4)
    (driver__ driver3)
    (obj_____ package7)
    (driver__ driver5)
    (path p0-1 s1)
    (locatable driver1)
    (locatable package10)
    (location s3)
    (at truck3 s1)
    (locatable driver4)
    (at package3 s3)
    (link s2 s1)
    (at truck4 s0)
    (injected-0)
  )
  (
    :goal
    (
      and
      (at driver2 s1)
      (at driver3 s3)
      (at driver4 s0)
      (at driver5 s0)
      (at truck4 s3)
      (at package1 s2)
      (at package2 s0)
      (at package3 s0)
      (at package4 s1)
      (at package5 s0)
      (at package6 s0)
      (at package7 s1)
      (at package8 s3)
      (at package9 s0)
      (at package10 s1)
      (injected-0)
    )
  )
)