(
  define
  (problem instance-2)
  (:domain driverlog)
  (:objects s3 p2-0 p5-4 truck4 package8 driver4 package10 s0 driver3 s5 p0-2 truck3 p1-3 p2-5 driver1 package9 truck2 package6 truck1 driver5 package5 p0-1 package7 s2 p3-5 package1 p3-4 package2 s1 p1-0 package3 package4 driver2 p0-5 s4)
  (
    :init
    (path p2-5 s5)
    (locatable truck3)
    (link s1 s5)
    (path s3 p3-5)
    (obj_____ package1)
    (at package6 s5)
    (link s0 s4)
    (locatable package6)
    (path s1 p0-1)
    (path s2 p2-5)
    (path p3-5 s3)
    (link s0 s2)
    (at package9 s4)
    (path s5 p2-5)
    (at driver5 s1)
    (empty truck3)
    (path p0-2 s0)
    (truck___ truck1)
    (locatable package4)
    (locatable driver2)
    (link s1 s3)
    (at package7 s0)
    (at package4 s3)
    (at truck4 s2)
    (link s2 s5)
    (at package1 s4)
    (locatable package7)
    (locatable truck2)
    (link s5 s1)
    (path s0 p0-1)
    (link s3 s0)
    (link s4 s0)
    (at package5 s2)
    (at package2 s5)
    (path s3 p1-3)
    (locatable driver3)
    (at driver2 s4)
    (obj_____ package10)
    (path p0-2 s2)
    (empty truck2)
    (at driver1 s0)
    (at package8 s2)
    (truck___ truck4)
    (path s0 p0-5)
    (link s2 s3)
    (obj_____ package2)
    (link s3 s4)
    (link s1 s4)
    (path p5-4 s4)
    (path s5 p0-5)
    (path p3-4 s3)
    (obj_____ package8)
    (link s3 s2)
    (link s4 s2)
    (obj_____ package6)
    (driver__ driver2)
    (at driver4 s4)
    (location s5)
    (location s1)
    (path s4 p5-4)
    (path s0 p0-2)
    (at truck2 s1)
    (link s3 s5)
    (link s4 s5)
    (link s2 s4)
    (link s4 s1)
    (link s5 s4)
    (at truck1 s5)
    (locatable package2)
    (path p0-5 s0)
    (locatable package9)
    (locatable package3)
    (link s4 s3)
    (locatable package8)
    (location p2-0)
    (location p0-1)
    (locatable truck1)
    (obj_____ package5)
    (location p3-4)
    (truck___ truck3)
    (location p2-5)
    (link s5 s2)
    (path p3-4 s4)
    (empty truck1)
    (at package10 s1)
    (location p3-5)
    (path p1-3 s1)
    (location s0)
    (driver__ driver1)
    (path s1 p1-3)
    (locatable truck4)
    (driver__ driver4)
    (locatable driver5)
    (path p0-5 s5)
    (truck___ truck2)
    (path s2 p0-2)
    (path p0-1 s0)
    (obj_____ package9)
    (obj_____ package3)
    (path p1-3 s3)
    (link s0 s3)
    (location p0-2)
    (empty truck4)
    (link s2 s0)
    (locatable package1)
    (at driver3 s3)
    (link s5 s3)
    (locatable package5)
    (location p0-5)
    (link s1 s2)
    (location s2)
    (location s4)
    (path s5 p3-5)
    (location p1-3)
    (location p5-4)
    (link s3 s1)
    (obj_____ package4)
    (path p5-4 s5)
    (at package3 s1)
    (driver__ driver3)
    (obj_____ package7)
    (path s3 p3-4)
    (path p2-5 s2)
    (path s4 p3-4)
    (driver__ driver5)
    (path p3-5 s5)
    (path p0-1 s1)
    (locatable driver1)
    (locatable package10)
    (location s3)
    (at truck3 s1)
    (path s5 p5-4)
    (locatable driver4)
    (link s2 s1)
    (location p1-0)
    (injected-0)
  )
  (
    :goal
    (
      and
      (at driver1 s5)
      (at driver3 s0)
      (at driver4 s0)
      (at truck2 s0)
      (at truck3 s2)
      (at truck4 s5)
      (at package1 s1)
      (at package2 s1)
      (at package3 s0)
      (at package4 s3)
      (at package5 s2)
      (at package6 s3)
      (at package7 s3)
      (at package8 s5)
      (at package9 s0)
      (at package10 s3)
      (injected-0)
    )
  )
)