(
  define
  (problem instance-4)
  (:domain driverlog)
  (:objects s3 truck5 truck7 p2-0 p5-4 truck9 truck4 package8 driver4 package10 truck8 s0 driver3 s5 p0-2 truck3 p1-3 p2-5 driver1 package9 truck2 package6 driver7 truck1 driver5 truck6 package5 p0-1 package7 s2 driver6 p3-5 package1 p3-4 package2 s1 p1-0 package3 package4 driver2 p0-5 s4)
  (
    :init
    (path p2-5 s5)
    (at truck8 s5)
    (at truck9 s0)
    (link s1 s5)
    (locatable truck3)
    (obj_____ package1)
    (link s0 s4)
    (locatable package6)
    (locatable truck9)
    (truck___ truck9)
    (link s0 s2)
    (at package9 s4)
    (truck___ truck1)
    (locatable driver2)
    (empty truck3)
    (path p0-2 s0)
    (link s1 s3)
    (empty truck9)
    (locatable package7)
    (locatable truck2)
    (link s5 s1)
    (at package1 s2)
    (path s0 p0-1)
    (link s3 s0)
    (link s4 s0)
    (locatable driver3)
    (at driver2 s4)
    (obj_____ package10)
    (empty truck2)
    (at driver1 s0)
    (path s0 p0-5)
    (link s2 s3)
    (obj_____ package2)
    (link s1 s4)
    (path p3-4 s3)
    (locatable driver6)
    (at truck1 s1)
    (driver__ driver2)
    (location s1)
    (link s3 s5)
    (link s4 s5)
    (locatable package2)
    (at package8 s5)
    (locatable package9)
    (link s4 s3)
    (location p0-1)
    (driver__ driver6)
    (obj_____ package5)
    (truck___ truck3)
    (location p2-5)
    (link s5 s2)
    (at driver6 s5)
    (location p3-5)
    (path p1-3 s1)
    (locatable truck4)
    (driver__ driver4)
    (locatable driver5)
    (truck___ truck2)
    (locatable truck8)
    (path s2 p0-2)
    (path p0-1 s0)
    (truck___ truck8)
    (obj_____ package3)
    (locatable truck6)
    (location p0-2)
    (location s4)
    (empty truck4)
    (locatable package1)
    (locatable package5)
    (location p0-5)
    (location s2)
    (empty truck8)
    (path s5 p3-5)
    (location p1-3)
    (empty truck6)
    (link s3 s1)
    (at truck3 s4)
    (obj_____ package4)
    (locatable truck7)
    (truck___ truck7)
    (locatable truck5)
    (path p2-5 s2)
    (driver__ driver5)
    (locatable package10)
    (path s5 p5-4)
    (locatable driver4)
    (empty truck7)
    (location p5-4)
    (link s2 s1)
    (empty truck5)
    (path s3 p3-5)
    (at driver7 s1)
    (path s1 p0-1)
    (path s2 p2-5)
    (path p3-5 s3)
    (locatable driver7)
    (path s5 p2-5)
    (at driver5 s1)
    (locatable package4)
    (link s2 s5)
    (at truck7 s2)
    (path s3 p1-3)
    (path p0-2 s2)
    (truck___ truck4)
    (link s3 s4)
    (at truck2 s2)
    (path s5 p0-5)
    (path p5-4 s4)
    (obj_____ package8)
    (link s3 s2)
    (link s4 s2)
    (obj_____ package6)
    (driver__ driver7)
    (truck___ truck6)
    (at driver4 s4)
    (at package7 s1)
    (location s5)
    (path s4 p5-4)
    (path s0 p0-2)
    (link s2 s4)
    (link s4 s1)
    (link s5 s4)
    (truck___ truck5)
    (path p0-5 s0)
    (locatable package3)
    (locatable package8)
    (location p2-0)
    (locatable truck1)
    (location p3-4)
    (at truck6 s3)
    (at package2 s4)
    (at truck5 s1)
    (path p3-4 s4)
    (empty truck1)
    (at package10 s5)
    (at package6 s3)
    (location s0)
    (at package5 s4)
    (driver__ driver1)
    (path s1 p1-3)
    (at truck4 s5)
    (path p0-5 s5)
    (obj_____ package9)
    (path p1-3 s3)
    (link s0 s3)
    (link s2 s0)
    (at driver3 s3)
    (link s5 s3)
    (link s1 s2)
    (path p5-4 s5)
    (at package3 s1)
    (driver__ driver3)
    (at package4 s4)
    (obj_____ package7)
    (path s3 p3-4)
    (path s4 p3-4)
    (path p3-5 s5)
    (path p0-1 s1)
    (locatable driver1)
    (location s3)
    (location p1-0)
    (injected-0)
  )
  (
    :goal
    (
      and
      (at driver1 s5)
      (at driver3 s0)
      (at driver4 s0)
      (at driver7 s0)
      (at truck1 s2)
      (at truck2 s5)
      (at truck3 s1)
      (at truck4 s1)
      (at truck5 s0)
      (at truck6 s3)
      (at truck7 s2)
      (at package1 s5)
      (at package2 s0)
      (at package3 s3)
      (at package4 s2)
      (at package5 s1)
      (at package6 s3)
      (at package7 s0)
      (at package8 s3)
      (at package9 s2)
      (at package10 s2)
      (injected-0)
    )
  )
)