(
  define
  (problem instance-3)
  (:domain mystery-strips)
  (:objects sciatica venus tuna bosnia popover chicken wonderbread arizona neptune papaya beef intoxication mutton turkey rest marzipan curiosity pistachio loneliness boils tomato bacon saturn grief anger hangover mars quebec muffin prostatitis rice kentucky onion understanding satisfaction aesthetics lubricity excitement potato triumph scallop love surrey cantelope abrasion goias snickers achievement angina alsace)
  (
    :init
    (pain loneliness)
    (eats pistachio muffin)
    (food wonderbread)
    (food snickers)
    (food mutton)
    (food beef)
    (eats papaya beef)
    (province goias)
    (pain hangover)
    (eats turkey mutton)
    (eats tuna rice)
    (eats onion turkey)
    (locale popover surrey)
    (pain angina)
    (eats tomato cantelope)
    (eats onion pistachio)
    (pleasure excitement)
    (food popover)
    (province kentucky)
    (province surrey)
    (eats tomato tuna)
    (harmony understanding neptune)
    (craves anger popover)
    (pleasure aesthetics)
    (craves hangover cantelope)
    (pleasure lubricity)
    (orbits mars saturn)
    (food cantelope)
    (craves achievement chicken)
    (food rice)
    (food tuna)
    (eats wonderbread marzipan)
    (food scallop)
    (pain grief)
    (craves lubricity wonderbread)
    (eats beef papaya)
    (eats mutton bacon)
    (eats beef tuna)
    (province arizona)
    (planet neptune)
    (eats beef scallop)
    (harmony excitement saturn)
    (orbits neptune mars)
    (province quebec)
    (eats muffin bacon)
    (food potato)
    (harmony curiosity saturn)
    (eats mutton turkey)
    (food marzipan)
    (harmony satisfaction mars)
    (eats turkey snickers)
    (craves excitement scallop)
    (eats snickers turkey)
    (attacks alsace goias)
    (pain prostatitis)
    (pleasure love)
    (craves sciatica papaya)
    (eats turkey chicken)
    (craves prostatitis muffin)
    (craves angina snickers)
    (locale wonderbread quebec)
    (eats wonderbread bacon)
    (locale beef kentucky)
    (planet mars)
    (eats potato snickers)
    (pleasure curiosity)
    (eats bacon muffin)
    (pain anger)
    (pleasure rest)
    (craves curiosity potato)
    (attacks surrey kentucky)
    (locale bacon arizona)
    (eats cantelope tomato)
    (food bacon)
    (eats onion mutton)
    (locale muffin alsace)
    (craves loneliness bacon)
    (province alsace)
    (attacks goias quebec)
    (harmony lubricity saturn)
    (locale onion goias)
    (craves abrasion beef)
    (planet venus)
    (food onion)
    (locale potato alsace)
    (food pistachio)
    (eats scallop chicken)
    (eats turkey wonderbread)
    (eats turkey onion)
    (locale papaya surrey)
    (locale tuna alsace)
    (harmony triumph saturn)
    (locale marzipan bosnia)
    (pain sciatica)
    (locale tomato alsace)
    (locale rice bosnia)
    (pleasure intoxication)
    (pain boils)
    (eats marzipan wonderbread)
    (pain abrasion)
    (eats chicken scallop)
    (eats tuna beef)
    (craves rest popover)
    (eats popover cantelope)
    (eats wonderbread turkey)
    (eats popover rice)
    (planet saturn)
    (food tomato)
    (eats chicken papaya)
    (craves aesthetics cantelope)
    (locale pistachio alsace)
    (eats papaya chicken)
    (locale cantelope goias)
    (eats pistachio onion)
    (eats rice tuna)
    (eats bacon mutton)
    (locale snickers goias)
    (locale chicken kentucky)
    (pleasure achievement)
    (craves love tomato)
    (food turkey)
    (food chicken)
    (eats scallop beef)
    (eats snickers potato)
    (harmony love neptune)
    (eats mutton onion)
    (food muffin)
    (locale mutton kentucky)
    (craves intoxication rice)
    (eats marzipan potato)
    (harmony achievement neptune)
    (locale scallop surrey)
    (pleasure triumph)
    (craves grief chicken)
    (eats tuna tomato)
    (eats bacon wonderbread)
    (pleasure understanding)
    (province bosnia)
    (attacks kentucky alsace)
    (attacks bosnia surrey)
    (craves boils onion)
    (eats cantelope popover)
    (craves satisfaction pistachio)
    (harmony intoxication mars)
    (eats potato marzipan)
    (food papaya)
    (eats rice popover)
    (eats muffin pistachio)
    (harmony aesthetics saturn)
    (attacks quebec arizona)
    (harmony rest saturn)
    (pleasure satisfaction)
    (craves understanding marzipan)
    (locale turkey alsace)
    (eats chicken turkey)
    (craves triumph turkey)
    (orbits venus neptune)
    (injected-0)
  )
  (
    :goal
    (
      and
      (craves anger turkey)
      (craves abrasion turkey)
      (injected-0)
    )
  )
)