(
  define
  (problem instance-5)
  (:domain mystery-strips)
  (:objects sciatica jealousy bosnia chicken pear quebec shrimp prostatitis kentucky neptune sweetroll lubricity cherry laceration manitoba pistachio loneliness dread boils tomato surrey bacon uranus hangover saturn alsace)
  (
    :init
    (craves dread bacon)
    (food shrimp)
    (pain loneliness)
    (eats pistachio chicken)
    (harmony lubricity saturn)
    (eats cherry chicken)
    (attacks alsace quebec)
    (attacks manitoba kentucky)
    (orbits uranus saturn)
    (pain hangover)
    (craves hangover chicken)
    (eats cherry pear)
    (food pistachio)
    (eats sweetroll tomato)
    (craves laceration pear)
    (attacks quebec bosnia)
    (craves boils tomato)
    (eats bacon pear)
    (craves sciatica shrimp)
    (locale cherry surrey)
    (attacks surrey manitoba)
    (pain sciatica)
    (province kentucky)
    (province surrey)
    (pain boils)
    (pleasure lubricity)
    (eats pear sweetroll)
    (craves jealousy pistachio)
    (eats shrimp tomato)
    (eats tomato shrimp)
    (planet saturn)
    (eats pistachio bacon)
    (orbits neptune uranus)
    (food tomato)
    (pain dread)
    (pain laceration)
    (eats shrimp chicken)
    (pain jealousy)
    (eats chicken shrimp)
    (eats tomato chicken)
    (locale sweetroll quebec)
    (planet neptune)
    (eats pear cherry)
    (province quebec)
    (province manitoba)
    (locale chicken kentucky)
    (locale bacon alsace)
    (planet uranus)
    (food chicken)
    (food cherry)
    (pain prostatitis)
    (craves prostatitis cherry)
    (food pear)
    (eats chicken pistachio)
    (locale pistachio surrey)
    (province bosnia)
    (eats tomato sweetroll)
    (eats pear bacon)
    (attacks bosnia surrey)
    (eats sweetroll pear)
    (locale shrimp manitoba)
    (eats bacon pistachio)
    (food sweetroll)
    (locale pear bosnia)
    (craves lubricity pear)
    (craves loneliness sweetroll)
    (food bacon)
    (eats chicken tomato)
    (locale tomato bosnia)
    (province alsace)
    (eats chicken cherry)
    (injected-0)
  )
  (
    :goal
    (
      and
      (craves laceration shrimp)
      (craves loneliness shrimp)
      (injected-0)
    )
  )
)