(
  define
  (problem instance-2)
  (:domain mystery-strips)
  (:objects sciatica tuna grief-2 shrimp arizona sweetroll intoxication turkey loneliness boils grief anger uranus hangover jealousy mars prostatitis kentucky earth broccoli depression satisfaction lubricity cherry laceration excitement scallop dread abrasion goias chocolate mercury anxiety angina alsace)
  (
    :init
    (orbits mercury earth)
    (pain loneliness)
    (food shrimp)
    (food broccoli)
    (craves grief-2 scallop)
    (orbits earth mars)
    (province goias)
    (pain hangover)
    (craves jealousy shrimp)
    (locale sweetroll alsace)
    (craves satisfaction broccoli)
    (eats scallop cherry)
    (pain angina)
    (locale turkey kentucky)
    (pleasure excitement)
    (harmony satisfaction earth)
    (province kentucky)
    (pain sciatica)
    (eats sweetroll shrimp)
    (pleasure intoxication)
    (craves excitement turkey)
    (pain boils)
    (craves anxiety broccoli)
    (eats tuna broccoli)
    (eats chocolate broccoli)
    (pain abrasion)
    (pleasure lubricity)
    (eats shrimp cherry)
    (eats tuna turkey)
    (harmony intoxication earth)
    (food tuna)
    (pain dread)
    (craves hangover scallop)
    (pain laceration)
    (food scallop)
    (eats scallop sweetroll)
    (pain jealousy)
    (eats turkey tuna)
    (locale chocolate goias)
    (eats cherry shrimp)
    (craves dread scallop)
    (pain anxiety)
    (eats sweetroll scallop)
    (pain grief-2)
    (harmony lubricity earth)
    (province arizona)
    (craves anger cherry)
    (eats chocolate turkey)
    (locale cherry kentucky)
    (craves abrasion turkey)
    (food turkey)
    (planet uranus)
    (craves grief broccoli)
    (food cherry)
    (craves prostatitis turkey)
    (pain prostatitis)
    (craves boils broccoli)
    (eats broccoli tuna)
    (orbits uranus mercury)
    (craves angina shrimp)
    (eats shrimp sweetroll)
    (craves sciatica broccoli)
    (craves intoxication tuna)
    (planet earth)
    (locale tuna arizona)
    (eats shrimp chocolate)
    (craves laceration shrimp)
    (planet mars)
    (food chocolate)
    (attacks alsace kentucky)
    (craves lubricity sweetroll)
    (pain anger)
    (attacks kentucky goias)
    (eats turkey chocolate)
    (eats cherry scallop)
    (pain depression)
    (food sweetroll)
    (harmony excitement mars)
    (locale shrimp kentucky)
    (locale scallop alsace)
    (planet mercury)
    (craves loneliness scallop)
    (pleasure satisfaction)
    (attacks goias arizona)
    (pain grief)
    (eats chocolate shrimp)
    (craves depression turkey)
    (locale broccoli arizona)
    (province alsace)
    (eats broccoli chocolate)
    (injected-0)
  )
  (
    :goal
    (
      and
      (craves loneliness shrimp)
      (craves grief shrimp)
      (injected-0)
    )
  )
)