(
  define
  (problem instance-4)
  (:domain mystery-strips)
  (:objects sciatica learning tuna bosnia wonderbread pepper hotdog turkey baguette rest pistachio tomato pork tofu anger uranus flounder hangover arugula bavaria muffin okra rice earth vulcan lobster aesthetics lubricity stimulation excitement triumph scallop love surrey pennsylvania cantelope abrasion goias jupiter anxiety achievement)
  (
    :init
    (eats hotdog okra)
    (eats rice tofu)
    (locale pork bosnia)
    (food wonderbread)
    (eats cantelope arugula)
    (eats scallop tomato)
    (province goias)
    (pain hangover)
    (eats arugula pistachio)
    (attacks goias pennsylvania)
    (eats tuna rice)
    (eats wonderbread flounder)
    (pleasure excitement)
    (eats wonderbread scallop)
    (craves abrasion baguette)
    (province surrey)
    (eats tomato scallop)
    (locale okra bosnia)
    (eats arugula cantelope)
    (pleasure aesthetics)
    (pleasure lubricity)
    (locale tofu goias)
    (food cantelope)
    (food rice)
    (eats okra wonderbread)
    (eats flounder lobster)
    (locale hotdog bavaria)
    (food tuna)
    (eats pepper pistachio)
    (harmony excitement jupiter)
    (food scallop)
    (eats tuna okra)
    (harmony aesthetics vulcan)
    (attacks bavaria goias)
    (eats muffin tofu)
    (food arugula)
    (eats tomato baguette)
    (craves anxiety muffin)
    (eats turkey pepper)
    (craves achievement rice)
    (eats pistachio arugula)
    (eats lobster flounder)
    (orbits uranus vulcan)
    (province pennsylvania)
    (eats okra hotdog)
    (locale flounder goias)
    (pleasure love)
    (locale rice bavaria)
    (eats baguette turkey)
    (locale pepper goias)
    (eats tofu rice)
    (food lobster)
    (craves excitement tomato)
    (planet jupiter)
    (eats rice muffin)
    (locale wonderbread goias)
    (food pork)
    (pleasure rest)
    (pain anger)
    (orbits vulcan jupiter)
    (craves anger baguette)
    (craves love okra)
    (craves learning cantelope)
    (food tofu)
    (harmony love jupiter)
    (eats wonderbread okra)
    (eats pistachio pepper)
    (craves stimulation muffin)
    (eats lobster pork)
    (locale turkey goias)
    (orbits earth uranus)
    (harmony achievement vulcan)
    (locale scallop pennsylvania)
    (locale cantelope pennsylvania)
    (craves hangover muffin)
    (locale muffin bavaria)
    (food pistachio)
    (province bavaria)
    (food okra)
    (eats tofu hotdog)
    (food baguette)
    (food flounder)
    (pain sciatica)
    (harmony lubricity uranus)
    (harmony stimulation uranus)
    (pain abrasion)
    (harmony rest jupiter)
    (food tomato)
    (eats tuna muffin)
    (eats muffin rice)
    (pain anxiety)
    (eats tofu muffin)
    (locale arugula bavaria)
    (craves aesthetics scallop)
    (eats rice tuna)
    (pleasure achievement)
    (eats flounder wonderbread)
    (food turkey)
    (eats scallop wonderbread)
    (planet uranus)
    (food muffin)
    (eats baguette tomato)
    (pleasure triumph)
    (planet earth)
    (eats okra tuna)
    (craves rest wonderbread)
    (province bosnia)
    (attacks bosnia surrey)
    (craves triumph hotdog)
    (eats hotdog tofu)
    (harmony triumph vulcan)
    (locale baguette bosnia)
    (craves sciatica okra)
    (eats turkey baguette)
    (pleasure stimulation)
    (eats pork lobster)
    (pleasure learning)
    (eats pepper turkey)
    (harmony learning vulcan)
    (eats cantelope pork)
    (locale lobster goias)
    (attacks pennsylvania bosnia)
    (craves lubricity arugula)
    (planet vulcan)
    (locale tuna surrey)
    (eats pork cantelope)
    (locale pistachio pennsylvania)
    (locale tomato bosnia)
    (food hotdog)
    (eats muffin tuna)
    (food pepper)
    (injected-0)
  )
  (
    :goal
    (
      and
      (craves anxiety wonderbread)
      (injected-0)
    )
  )
)