(
  define
  (problem instance-1)
  (:domain mystery-strips)
  (:objects venus ham jealousy bavaria popover lemon pepper depression entertainment snickers satisfaction arizona guanabara vulcan anxiety pea melon neptune laceration mutton manitoba marzipan triumph love boils goias grief chocolate hangover angina orange)
  (
    :init
    (craves satisfaction mutton)
    (eats pepper melon)
    (eats chocolate ham)
    (food snickers)
    (food mutton)
    (craves boils melon)
    (province goias)
    (locale snickers bavaria)
    (planet venus)
    (pain hangover)
    (food lemon)
    (craves triumph popover)
    (orbits vulcan venus)
    (eats pea lemon)
    (province bavaria)
    (eats popover marzipan)
    (locale orange bavaria)
    (locale chocolate guanabara)
    (eats snickers marzipan)
    (pain angina)
    (craves entertainment pepper)
    (food popover)
    (locale pepper manitoba)
    (locale mutton guanabara)
    (pleasure entertainment)
    (craves hangover chocolate)
    (attacks goias guanabara)
    (locale popover arizona)
    (eats melon mutton)
    (eats marzipan snickers)
    (pain boils)
    (harmony triumph neptune)
    (eats lemon pea)
    (eats orange chocolate)
    (pain laceration)
    (eats lemon popover)
    (eats marzipan pea)
    (eats pepper pea)
    (pain jealousy)
    (craves angina orange)
    (pain anxiety)
    (craves anxiety snickers)
    (province arizona)
    (planet neptune)
    (eats orange mutton)
    (craves love orange)
    (eats popover pepper)
    (harmony satisfaction neptune)
    (eats pea pepper)
    (province manitoba)
    (harmony love neptune)
    (food ham)
    (food marzipan)
    (attacks arizona manitoba)
    (pleasure love)
    (locale lemon goias)
    (pleasure triumph)
    (craves jealousy ham)
    (locale pea bavaria)
    (harmony entertainment venus)
    (attacks bavaria arizona)
    (eats pea snickers)
    (food chocolate)
    (eats chocolate orange)
    (locale marzipan bavaria)
    (attacks guanabara bavaria)
    (eats pea marzipan)
    (food orange)
    (craves depression popover)
    (province guanabara)
    (eats mutton orange)
    (pain depression)
    (food pea)
    (locale melon manitoba)
    (eats melon ham)
    (craves grief marzipan)
    (eats snickers pea)
    (eats melon pepper)
    (planet vulcan)
    (food melon)
    (eats ham chocolate)
    (eats marzipan popover)
    (eats pepper popover)
    (eats popover lemon)
    (pleasure satisfaction)
    (eats mutton melon)
    (craves laceration pepper)
    (pain grief)
    (eats ham melon)
    (locale ham manitoba)
    (orbits venus neptune)
    (food pepper)
    (injected-0)
  )
  (
    :goal
    (
      and
      (craves hangover ham)
      (injected-0)
    )
  )
)