(
  define
  (problem instance-2)
  (:domain ferry)
  (:objects l0 l1 l2 c1 c2 c4 l4 c0 c3 l3 l5)
  (
    :init
    (not-eq l2 l4)
    (not-eq l3 l5)
    (not-eq l0 l3)
    (at-ferry l1)
    (not-eq l5 l1)
    (location l5)
    (not-eq l0 l4)
    (at c1 l2)
    (at c3 l2)
    (not-eq l3 l2)
    (not-eq l3 l4)
    (not-eq l2 l3)
    (not-eq l2 l0)
    (at c0 l5)
    (location l4)
    (not-eq l0 l1)
    (location l2)
    (not-eq l4 l5)
    (car c0)
    (not-eq l1 l5)
    (not-eq l3 l0)
    (at c2 l2)
    (not-eq l4 l2)
    (location l3)
    (location l0)
    (not-eq l2 l1)
    (empty-ferry)
    (car c2)
    (not-eq l1 l2)
    (not-eq l1 l4)
    (not-eq l5 l4)
    (car c1)
    (not-eq l5 l2)
    (not-eq l4 l3)
    (not-eq l4 l0)
    (not-eq l3 l1)
    (car c3)
    (not-eq l0 l5)
    (location l1)
    (not-eq l1 l3)
    (not-eq l1 l0)
    (not-eq l5 l3)
    (not-eq l5 l0)
    (not-eq l0 l2)
    (not-eq l2 l5)
    (at c4 l2)
    (car c4)
    (not-eq l4 l1)
    (injected---0)
  )
  (
    :goal
    (
      and
      (at c0 l4)
      (at c1 l4)
      (at c2 l3)
      (at c3 l5)
      (at c4 l4)
      (injected---0)
    )
  )
)